"""Add currency table

Revision ID: 64148bc92dbc
Revises: 06cfde537d0a
Create Date: 2024-10-18 18:13:14.547903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64148bc92dbc'
down_revision: Union[str, None] = '06cfde537d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_update', sa.String(), nullable=True),
    sa.Column('base', sa.String(), nullable=False),
    sa.Column('rub', sa.String(), nullable=False),
    sa.Column('eur', sa.String(), nullable=False),
    sa.Column('usd', sa.String(), nullable=False),
    sa.Column('jpy', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_table('currency')
    # ### end Alembic commands ###
